{{ if eq .Values.invoker.containerFactory.impl "docker" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-watcher-nodes-list
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Release.Name }}-watcher
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-nodes-list
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-watcher-pods-list
  labels:
{{ include "openwhisk.label_boilerplate" . | indent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Release.Name }}-watcher
roleRef:
  kind: Role
  name: {{ .Release.Name }}-pods-list
  apiGroup: rbac.authorization.k8s.io
{{- end }}
