service: dataLocality

provider:
  name: openwhisk
  runtime: nodejs:12
  ignore_certs: true

functions:
  dataLocality:
    memory: 512
    handler: index.main
    annotations:
      parameters:
        - tag: 'mongoDB'
    events:
      - http:
          path: /dataLocality
          method: post
          resp: json
  dataLocality_noCTag:
    memory: 512
    handler: index.main
    annotations:
      parameters:
        - tag: 'mongoDB'
    events:
      - http:
          path: /dataLocality_noCTag
          method: post
          resp: json
plugins:
  - serverless-openwhisk
